# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d9129cf83195cb093ac7f3c5c588b020013f62b7747c7683135dde154fcbe4e117a29ca694d2c0ab5c04087fcfecf0473b2a628b03b6cd82194841781651575

test:
  secret_key_base: 50b4d9308c783d1fbf22441dfe81c021b97b13f6c58ee908206047b4a684f4df9b9d78f982bcb6bf48fd9eb4a38ef279ca429ea0e409540118483a6a145d0989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
